# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @export
fixB <- function(B, R) {
    invisible(.Call(`_bifacL1rot_fixB`, B, R))
}

freeR <- function(R) {
    .Call(`_bifacL1rot_freeR`, R)
}

commutation_matrix <- function(p, q) {
    .Call(`_bifacL1rot_commutation_matrix`, p, q)
}

ALM_cpp <- function(A, Bstart_ = NULL, Phi_ = NULL, rho = 1.0, t = 0.001, maxit_ou = 5000L, maxit_in = 300L, orthogonal = FALSE, tol1 = 1e-6, tol2 = 1e-4, verbose = TRUE, v_every = 10L, Lmax = 20.0, c1 = 1.05, c2 = 0.25) {
    .Call(`_bifacL1rot_ALM_cpp`, A, Bstart_, Phi_, rho, t, maxit_ou, maxit_in, orthogonal, tol1, tol2, verbose, v_every, Lmax, c1, c2)
}

